// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check if the API is running and healthy",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/socket": {
            "get": {
                "description": "Establishes a WebSocket connection for receiving video frames. Send binary frames to the server, and receive text responses back.\n\n**Client Flow:**\n1. Connect to the WebSocket endpoint (ws://localhost:8080/socket)\n2. Send video frames as binary messages (MessageBinary)\n3. Server buffers frames and sends batches of 32 to processing API\n4. Receive text responses as JSON messages (MessageText)\n\n**Response Format:**\nThe server sends back JSON text messages with the structure:\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"text\": \"extracted or processed text from the frames\"\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n**Frontend Example:**\n` + "`" + `` + "`" + `` + "`" + `javascript\nconst ws = new WebSocket('ws://localhost:8080/socket');\n\n// Send binary frame data\nws.send(frameDataBlob);\n\n// Receive text messages\nws.onmessage = (event) =\u003e {\nconst data = JSON.parse(event.data);\nconsole.log('Received text:', data.text);\n};\n` + "`" + `` + "`" + `` + "`" + `",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websocket"
                ],
                "summary": "WebSocket endpoint for video frame streaming",
                "responses": {
                    "101": {
                        "description": "WebSocket response with extracted text",
                        "schema": {
                            "$ref": "#/definitions/api.WebSocketMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Failed to accept websocket",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "Upload a video file, extract frames, and process them in batches of 32 frames. Unlike the WebSocket endpoint, this processes the entire video at once and returns a summary.\n\n**Process Flow:**\n1. Upload video file via multipart form data\n2. Server extracts frames from the video\n3. Frames are split into batches of 32\n4. Each batch is sent sequentially to the processing API\n5. Returns processing summary with statistics\n\n**Response Format:**\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"status\": \"completed\",\n\"total_frames\": 250,\n\"total_batches\": 8,\n\"successful_batches\": 8,\n\"video_info\": {\n\"fps\": 25.0,\n\"duration\": 10.0,\n\"frame_width\": 1920,\n\"frame_height\": 1080,\n\"estimated_frames\": 250\n}\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n**Frontend Example:**\n` + "`" + `` + "`" + `` + "`" + `javascript\nconst formData = new FormData();\nformData.append('video', videoFile);\nformData.append('interval', '1'); // Optional: extract every Nth frame\n\nconst response = await fetch('http://localhost:8080/upload', {\nmethod: 'POST',\nbody: formData\n});\n\nconst result = await response.json();\nconsole.log('Processing completed:', result);\n` + "`" + `` + "`" + `` + "`" + `",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "Upload video for frame-by-frame processing",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Video file to process",
                        "name": "video",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Frame extraction interval (default: 1, extract every frame)",
                        "name": "interval",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Processing result with status and metadata",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid file or format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.WebSocketMessage": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "ws"},
	Title:            "Video Streaming API",
	Description:      "API for video frame streaming and processing via WebSocket and video upload",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
